// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK4jjrMy5maDMJuqiJ52IiNonIrUJBkNw',
    appId: '1:349772102267:web:eb3c68bc395722349f40de',
    messagingSenderId: '349772102267',
    projectId: 'photomap-c92bb',
    authDomain: 'photomap-c92bb.firebaseapp.com',
    storageBucket: 'photomap-c92bb.appspot.com',
    measurementId: 'G-JW74GT97GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfy53YrR52GnMO-NNITxui6vC3_R6v0yE',
    appId: '1:349772102267:android:c44cebf2697361379f40de',
    messagingSenderId: '349772102267',
    projectId: 'photomap-c92bb',
    storageBucket: 'photomap-c92bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkOev2UNEnpIsaa3rS8M539sf5oW-DiZQ',
    appId: '1:349772102267:ios:acc54635c1b3be099f40de',
    messagingSenderId: '349772102267',
    projectId: 'photomap-c92bb',
    storageBucket: 'photomap-c92bb.appspot.com',
    iosClientId: '349772102267-c2sfa51eamk1n6b2f25fe5bnq4gg435p.apps.googleusercontent.com',
    iosBundleId: 'com.example.photomap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkOev2UNEnpIsaa3rS8M539sf5oW-DiZQ',
    appId: '1:349772102267:ios:acc54635c1b3be099f40de',
    messagingSenderId: '349772102267',
    projectId: 'photomap-c92bb',
    storageBucket: 'photomap-c92bb.appspot.com',
    iosClientId: '349772102267-c2sfa51eamk1n6b2f25fe5bnq4gg435p.apps.googleusercontent.com',
    iosBundleId: 'com.example.photomap',
  );
}
